### ISSUE TITLE
[Feature Request]: Potentially scale menu assets (such as personas, or the models of the protagonist in menus)?

### ISSUE THREAD

**Issue by Xbob42** [Lyall/P3RFix#17]
## Feature Summary:
A way to render menu assets at the correct resolution.

### Is your proposal related to a problem?
The problem is aliased and blurry menu assets at higher resolutions, such as persona models, all the neat little transition effects that use 3D assets (like the protagonist), etc. To be clear, the issue is with _the game_, not with this fix, I'm just hoping the fix can potentially address it. :)

### Describe the solution you'd like
While I hope it's not a red herring or anything (I'm just a layman), Tales of Arise was also a UE4 game and had what appears to be an identical issue. In that game, it was for skits, which are like little cutscenes that play out in comic-book style frames, but still using 3D models. The person who made the fix for that game identified the problem as "UTextureRenderTarget2D" not scaling properly to your resolution, so the skits by default looked -- you guessed it: aliased and blurry at higher resolutions.

**Comment by Lyall** [comment]
I've been looking at this here and there and while I can find where the render targets were created and increase the resolution, the result is that the texture isn't scaled correctly. I'll still need to do more research to see if it can be scaled correctly after.

Here's an example, the Persona model preview is 1024x1024. If you were to scale it up to 2048x2048, then it looks like this.

![P3R_2024_02_14_12_40_17_934](https://github.com/Lyall/P3RFix/assets/695941/7fb79e69-7f2d-4b7a-a285-029194b3894a)
![P3R_2024_02_14_12_40_22_110](https://github.com/Lyall/P3RFix/assets/695941/b8be31a8-60b6-431e-90c6-912aae6f3a11)

**Comment by Lyall** [comment]
Okay I had a further look at [emoose's work](https://gist.github.com/emoose/460a9d509b767af39ce6acc611f9233e) on Bloodstained and was able to apply that here. Here is how that same screen looks at 4096x4096.

![image](https://github.com/Lyall/P3RFix/assets/695941/2d7c7f31-5b7a-4820-be2a-c3e5247467fc)

**Comment by Xbob42** [comment]
Incredible! That looks SO much better!

**Comment by Drahsid** [comment]
Don't see any commits related to your last picture, so this all may be redundant. 
Something that would probably be ideal here is to adjust the resolution of the UTextureRenderTarget2D based on the ratio of 1080p and the user's resolution and screen percentage, and subsequently scale it to fit the correct size.
For this, it's probably only worth considering the smallest axis (because of bonkers aspect ratios.) For example, at 3840x2160 and 150% screen percentage, the ratio would be `(2160 * 1.5) / 1080 = 3`. Based on this, the dimensions of the UTextureRenderTarget2D would be multiplied by 3, and would be scaled by 1 / 3.
This should in theory make the appearance of everything using UTextureRenderTarget2D consistent.

**Comment by Lyall** [comment]
> Don't see any commits related to your last picture, so this all may be redundant. Something that would probably be ideal here is to adjust the resolution of the UTextureRenderTarget2D based on the ratio of 1080p and the user's resolution and screen percentage, and subsequently scale it to fit the correct size. For this, it's probably only worth considering the smallest axis (because of bonkers aspect ratios.) For example, at 3840x2160 and 150% screen percentage, the ratio would be `(2160 * 1.5) / 1080 = 3`. Based on this, the dimensions of the UTextureRenderTarget2D would be multiplied by 3, and would be scaled by 1 / 3. This should in theory make the appearance of everything using UTextureRenderTarget2D consistent.

That seems like a good idea on how to have it configured going forward. It does seem like the UI is generally targeted towards 1080p based on everything I've seen so I think what you posted makes a lot of sense. I've already got hooks for both the resolution and screen percentage, so getting those values is trivial. 

The only problem at the moment is that just setting a universal multiplier is causing issues. For example, the main menu in-game is a render to texture at 1920x1080. If you scale that up it ends up displaying incorrectly. Also, the minimap breaks and some battle overlays seem to break. For just now I've only got it working reliably with the persona model preview. That displays at 1024x1024 by default.

**Comment by Drahsid** [comment]
> The only problem at the moment is that just setting a universal multiplier is causing issues. For example, the main menu in-game is a render to texture at 1920x1080. If you scale that up it ends up displaying incorrectly.
What sort of incorrect display?

Are you using a similar hook as in emoose's work? `UTextureRenderTarget2D::ResizeTarget` might have better results than just changing the size directly since it also enqueues a command to update the resource (though I am not sure when PostLoad runs, so this could be redundant.)
I wonder if the PS5 build just has different magic numbers in their code for this, or if they made it more modular somewhere up the call chain.

**Comment by Lyall** [comment]
>  What sort of incorrect display?
Well the minimap is completely black and the game menu shows up as a quarter size box when using a 4x multiplier. 

> Are you using a similar hook as in emoose's work? `UTextureRenderTarget2D::ResizeTarget` might have better results than just changing the size directly since it also enqueues a command to update the resource (though I am not sure when PostLoad runs, so this could be redundant.) I wonder if the PS5 build just has different magic numbers in their code for this, or if they made it more modular somewhere up the call chain.

I'm hooking `UTextureRenderTarget2D::PostLoad'. Had trouble finding the other functions, I need to see if I can get an SDK dumper working.

**Comment by Bayzen11** [comment]
> Okay I had a further look at [emoose's work](https://gist.github.com/emoose/460a9d509b767af39ce6acc611f9233e) on Bloodstained and was able to apply that here. Here is how that same screen looks at 4096x4096.
> 
> ![image](https://private-user-images.githubusercontent.com/695941/304830970-2d7c7f31-5b7a-4820-be2a-c3e5247467fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NTkzMDQsIm5iZiI6MTcwNzk1OTAwNCwicGF0aCI6Ii82OTU5NDEvMzA0ODMwOTcwLTJkN2M3ZjMxLTViN2EtNDgyMC1iZTJhLWMzZTUyNDc0NjdmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQwMTAzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTRlMWIzN2M0MWZmNjdjOGQxZWMxNjE0MjVhNzQyNTVjMTczNjdiNjE3ZmNmN2U2ZjU5MTI3ZDhhMTdjOWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YC7k9qTMUfpYqQ-vkl3Eg_U559-9E-DojsDA0Su1yZo)

This is awesome, looking at these personas has been an eyesore, I hope you can at least include this UI Persona scaler in the next version of your P3R Fix if it doesn't have any bugs

**Comment by SandeMC** [comment]
As an addition to this, is it possible to apply some AA pass to these? Even at 1080p, the edges are really sharp and noticeable

**Comment by Drahsid** [comment]
Alright, so I think I actually fixed (most) of the issues with the following code:
`
static SafetyHookMid RenTex2DMidHook{};
RenTex2DMidHook = safetyhook::create_mid(RenTex2DScanResult,
[](SafetyHookContext& ctx)
{
	if ((ctx.rcx + 0x180) && (ctx.rcx + 0x184))
	{
		int* pRenTexSizeX = reinterpret_cast<int*>(ctx.rcx + 0x180);
		int* pRenTexSizeY = reinterpret_cast<int*>(ctx.rcx + 0x184);
		int iRenTexSizeX = *pRenTexSizeX;
		int iRenTexSizeY = *pRenTexSizeY;
		float fRenTexRatioX = (float)iRenTexSizeX / (float)iRenTexSizeY;
		float fRenTexRatioY = (float)iRenTexSizeY / (float)iRenTexSizeX; // also 1 / X
		if (   (iRenTexSizeX >= 32 && iRenTexSizeX < iCustomResX)
			|| (iRenTexSizeY >= 32 && iRenTexSizeY < iCustomResY))
		{
			int iMaxTexSize = 4096; // can technically go up to 16384, however anything past 4096 causes notable stutters when the render texture is loaded 

			spdlog::info("----------");
			spdlog::info("Render Texture 2D: X {:d}, Y {:d}, Ratio {:f}", iRenTexSizeX, iRenTexSizeY, fRenTexRatioX);

			if (fRenTexRatioX == fAspectRatio) {
				spdlog::info("Render Texture 2D has same aspect as screen: {:d}, {:d}", iRenTexSizeX, iRenTexSizeY);
			}

			if (iRenTexSizeX == 1920 && iRenTexSizeY == 1080) {
				// Seems to affect pause menu screens, has some minor bugs in transitions
				float fRenderScale = fScreenPercentage / 100.0f;
				iRenTexSizeX = iCustomResX * fRenderScale;
				iRenTexSizeY = iCustomResY * fRenderScale;
				spdlog::info("Render Texture 2D screen percent: {:f}, {:d}x{:d}", fRenderScale, iCustomResX, iCustomResY);
			}
			else if (iRenTexSizeX > iRenTexSizeY) {
				// generic X > Y
				iRenTexSizeX *= fRenTexResMultiX;
				if (iRenTexSizeX > iMaxTexSize) {
					iRenTexSizeX = iMaxTexSize;
				}
				iRenTexSizeY = iRenTexSizeX * fRenTexRatioX;
			}
			else if (iRenTexSizeY > iRenTexSizeX) {
				// generic Y > X
				iRenTexSizeY *= fRenTexResMultiY;
				if (iRenTexSizeY > iMaxTexSize) {
					iRenTexSizeY = iMaxTexSize;
				}
				iRenTexSizeX = iRenTexSizeY * fRenTexRatioY;
			}
			else {
				// generic 1:1
				iRenTexSizeX *= fRenTexResMultiY;
				iRenTexSizeY *= fRenTexResMultiY;
				if (iRenTexSizeX > iMaxTexSize) {
					iRenTexSizeX = iRenTexSizeY = iMaxTexSize;
				}
			}

			*pRenTexSizeX = iRenTexSizeX;
			*pRenTexSizeY = iRenTexSizeY;

			spdlog::info("Render Texture 2D new size: {:d}, {:d}", iRenTexSizeX, iRenTexSizeY);
		}
	}
});
`
Only change not listed here is that I split `fRenTexResMulti` into separate X and Y scales, and adjusted the calculation to not be subject to int promotion:
`
fRenTexResMultiX = (((float)iCustomResX) * (fScreenPercentage / 100.0f)) / 1080.0f;
fRenTexResMultiY = (((float)iCustomResY) * (fScreenPercentage / 100.0f)) / 1080.0f;
`

In some quick testing, the only visual errors I am encountering with this is that in certain transitions, the game uses a 1920x1080 clipping rect, so at 4k, it appears as a box in the top left corner.

Not related but I noticed the log outputting the following:
`
[info] Custom Resolution: iCustomResX: 2560
[info] Custom Resolution: iCustomResY: 1440
[info] Custom Resolution: fHUDWidth: 2560
[info] Custom Resolution: fHUDHeight: 1440
`
The display the game is on is 2160p, so I wonder if there's an oopsie in which desktop you're checking for the resolution initially.

**Comment by Drahsid** [comment]
I recorded a quick video illustrating my changes. At the start I am illustrating the worst case for the 1080p clip rects I have seen. After that, I go through the pause menu, and into the velvet room. The video: https://youtu.be/RFTeLMdHlR8

**Comment by Drahsid** [comment]
> Are you using multiple displays with the game on your non-primary display?
No, the game is on my  primary display, and I'm not doing any weird surround stuff.
The following is my display layout:
![image](https://github.com/Lyall/P3RFix/assets/19179468/4e4369c1-a790-4066-877d-3602149efcd4)
Display 3 is the primary display, and is 3840x2160, the top display is 2560x1440, and the right display is 1920x1080.

**Comment by Lyall** [comment]
> No, the game is on my primary display, and I'm not doing any weird surround stuff. The following is my display layout: <snip>
Display 3 is the primary display, and is 3840x2160, the top display is 2560x1440, and the right display is 1920x1080.

Hmm. not sure why it would be grabbing the rect of that display of all things. The docs explicitly state it's supposed to grab height and width of the primary monitor. Does it happen everytime? Also you've got the width and height set to 0 in the config so it's definitely using the GetWindowRect() result right?

**Comment by Drahsid** [comment]
> Also you've got the width and height set to 0 in the config so it's definitely using the GetWindowRect() result right?
Yeah, those values are set to 0. I'm not sure why is happens.

**Comment by Lyall** [comment]
Ah you know what it probably is. The bane of all existence, are you using DPI scaling?

**Comment by Drahsid** [comment]
Oh god damn it, that's probably it.

**Comment by Xbob42** [comment]
Hahaha, that got a chuckle out of me since DPI scaling has been nothing but trouble for me since I turned it on.

**Comment by Lyall** [comment]
It's good that we've caught it though. I wonder if compiling it with DPI Awareness enabled would solve this.

![image](https://github.com/Lyall/P3RFix/assets/695941/dfde31b9-57e1-4a8d-ab1f-2c3f4b487b2b)

Do you want to give it a try on your end @Drahsid?

**Comment by Drahsid** [comment]
> It's good that we've caught it though. I wonder if compiling P3RFix with DPI Awareness enabled would solve this.
> 
> ![image](https://private-user-images.githubusercontent.com/695941/305172132-dfde31b9-57e1-4a8d-ab1f-2c3f4b487b2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTk4NzIsIm5iZiI6MTcwODAxOTU3MiwicGF0aCI6Ii82OTU5NDEvMzA1MTcyMTMyLWRmZGUzMWI5LTU3ZTEtNGE4ZC1hYjFmLTJjM2Y0YjQ4N2IyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxNzUyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmU2ZmE4ZjEyMjY4MzE0ZDMyMDQyZWI5ZGRlNzQ5YTcwNTY2MDM2ZTU3YWE4YjUxZDI1ZmVkOTgwYThjYTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g-uttkydDWEboS7K1r7YrwGFP4KQRAHYjnhIrMT6QVI)
> 
> Do you want to give it a try on your end @Drahsid?

This doesn't fix the issue, however, telling the windows that P3R applies DPI scaling on it's own does.

**Comment by Drahsid** [comment]
In your recent update you fixed the clipping in transitions, that's awesome, great work!
Something that I thought of when testing this is that it may be useful to have the `Multiplier` variable become relative to the user's resolution if it is nonzero, and `Render Texture Resolution` is enabled (or something like that). The use of this could be that if the user is already calculating the optimal resolution based on their display resolution and screen %, they might want to further super sample the UI elements, since it should have less performance impact than doing so for the rest of the game.
A quick test that I did to implement this on my end was I made another "Multiplier2" config value, which is applied when multiplying the iRenTexSizes:
```cpp
iRenTexSizeX *= (fRenTexResMulti * fRenTexResMulti2);
iRenTexSizeY *= (fRenTexResMulti * fRenTexResMulti2);
```
This is certainly a better way to design this, but this might make stuff look really good for people who can and want to super sample, and it still gives the option to be reduce the resolution relative to the used resolution instead of 1080p

**Comment by Lyall** [comment]
> In your recent update you fixed the clipping in transitions, that's awesome, great work! 

Yeah I ended up just skipping a specific render texture (RT_Capture). It seems to be the only one that has the RenderTextureFormat set to `RTF_RGBA16f`. Not sure on the technical reason why it uses that format, perhaps maybe to do with alpha transparency as it "melts away" in the transition? I was able to find some parts of code that allowed me to change the size but even set to match the new render texture size it was still off slightly. Maybe it bears more investigation at a later date as that capture is still limited to 1080p.

>Something that I thought of when testing this is that it may be useful to have the `Multiplier` variable become relative to the user's resolution if it is nonzero, and `Render Texture Resolution` is enabled (or something like that). The use of this could be that if the user is already calculating the optimal resolution based on their display resolution and screen %, they might want to further super sample the UI elements, since it should have less performance impact than doing so for the rest of the game. A quick test that I did to implement this on my end was I made another "Multiplier2" config value, which is applied when multiplying the iRenTexSizes:
> 
> ```c++
> iRenTexSizeX *= (fRenTexResMulti * fRenTexResMulti2);
> iRenTexSizeY *= (fRenTexResMulti * fRenTexResMulti2);
> ```
> 
> This is certainly a better way to design this, but this might make stuff look really good for people who can and want to super sample, and it still gives the option to be reduce the resolution relative to the used resolution instead of 1080p

I may be just misunderstanding with my lack of sleep-addled brain but doesn't `fRenTexResMulti` already accomplish this? If it is set to 0, it's calculated based off screen resolution + screen percentage. If it's not set to 0, it becomes a configurable multiplier on both axes.

I've commented on the PR comment that was made about this but it's useful to talk about here too. The stuttering that occurs when the "actor preview" render textures are created at >= 4096x4096 - I'm assuming it's happening because each time you scroll through those personae it's creating a fresh render texture each time. One thing to help with that might be to try and apply anti-aliasing. Looking at the in-house plugin they use for it, the render texture appears to have the showflag setting for anti-aliasing disabled. 

```ini
"ShowFlagSettings": [
        {
          "ShowFlagName": "BSP",
          "Enabled": false
        },
        {
          "ShowFlagName": "AntiAliasing",
          "Enabled": false
        },
<snip>
```

Oh also @Drahsid, I changed the method of grabbing the desktop resolution in [a675bde](https://github.com/Lyall/P3RFix/commit/a675bde3523afec2ae944410e8931254158bb636). Are you able to test this out on your end? I couldn't get it to misreport the desktop resolution with DPI scaling on even prior to changing methods so I'm unable to test.

**Comment by Drahsid** [comment]
> I may be just misunderstanding with my lack of sleep-addled brain but doesn't fRenTexResMulti already accomplish this?

Sorry, what I wrote may have been unclear. What I was describing was giving the user the option to supersample the render texture elements further than whatever their screen percentage setting is, while still working in terms relative to their screen resolution and render scale. Since most of the render textures are UI related, or otherwise not the size of the viewport, I don't think this will have an insane performance impact unless somebody puts uses totally unreasonable value.

So for example, the user could be playing at 1080p, with their render scale at 150%, where the whole game effectively renders at 1620p. 
What I am suggesting is giving the user the option to subsequently scale the render textures again for a much crisper UI. Basically, a second render scale for the render textures. Say this same user set this value to 200%, this would then make it so their UI is being drawn as if they were at 3240p, and they wouldn't need to manually do the math with the existing variable, where setting it to 3 would have the same result.

> I've commented on the PR comment that was made about this but it's useful to talk about here too. The stuttering that occurs when the "actor preview" render textures are created at >= 4096x4096. One thing to help with that might be to try and apply anti-aliasing. Looking at the in-house plugin they use for it, the render texture appears to have the showflag setting for anti-aliasing disabled.

I am pretty sure this stutter happens because every time the preview is changed they completely throw out the render texture and allocate a new one. Being so large might also cause some nonsense with virtual textures, which could certainly contribute.

> Oh also @Drahsid, I changed the method of grabbing the desktop resolution in [a675bde](https://github.com/Lyall/P3RFix/commit/a675bde3523afec2ae944410e8931254158bb636). Are you able to test this out on your end? I couldn't get it to misreport the desktop resolution with DPI scaling on even prior to changing methods so I'm unable to test.

This works on my end!

**Comment by Lyall** [comment]
Okay I've added what you suggested in [v1.1.2](https://github.com/Lyall/P3RFix/releases).

```ini
[Render Texture Resolution]
; Increases resoluton for TextureRenderTarget2D objects such as character models in menus etc.
; Leave multiplier at 1 to use the automatically calculated resolution multiplier, or adjust above or below 1 to supersample/undersample further.
Enabled = true
Multiplier = 1
```
Here's the relevant part of code:
```cpp
    // Calculate optimal resolution multiplier assuming target is 1080p
    // Screen percentage is only retrieved when the hook is run, meaning that on first boot we have to assume it is 100%
    float fOptimalRenTexResMulti = (iCustomResY * (fScreenPercentage / 100)) / 1080;
    float fRenTexResMulti;

    if (fRenTexResUserMulti == 1.0f)
    {
        // If set to 1, use the calculated optimal multiplier.
        fRenTexResMulti = fOptimalRenTexResMulti;
    }
    else
    {
        // If not set to 1, then multiply on top using user defined value.
        fRenTexResMulti = fOptimalRenTexResMulti * fRenTexResUserMulti;
    }

    // Min = 25%, Max = 400%
    fRenTexResMulti = std::clamp(fRenTexResMulti, (float)0.25, (float)4);
    spdlog::info("Render Texture 2D Resolution: fRenTexResMulti = {}", fRenTexResMulti);
```
I was also able to address the stuttering in this version, I've tried up to 8K without seeing obvious stuttering (massive GPU load though!). Some HUD elements will still be limited to your screen resolution though as they cause issues going too high. Also the render texture that caused the clipped rect issue is still only 1080p. 

Good to hear the new method of grabbing the desktop res skips the DPI stuff, I'll use it going forward.

**Comment by Drahsid** [comment]
Awesome stuff. I think the only problem that really remains for this issue, now, is that the RT_Capture captures at 1080p. It is probably worth noting that it is still effected by supersampling. I wonder if this is an option we could just change within the asset itself.

**Comment by SandeMC** [comment]
> As an addition to this, is it possible to apply some AA pass to these? Even at 1080p, the edges are really sharp and noticeable (though, technically setting the multiplier to 1.5x would fix this too)

Supersampling to 2x works too

**Comment by Lyall** [comment]
> Awesome stuff. I think the only problem that really remains for this issue, now, is that the RT_Capture captures at 1080p. It is probably worth noting that it is still effected by supersampling. I wonder if this is an option we could just change within the asset itself. Edit: Looks like somebody added an issue for this, #26

Yeah, not 100% sure on how to tackle this. I think for now though, given that this issue was mostly addressed, we'll move discussion of these further problems to the other issue thread (#26) so I'm going to close this one.
